### ISSUE TITLE
dead loop? bug?

### ISSUE THREAD

**Issue by abc100m** [simdsoft/yasio#1]
int xxsocket::send(void\* buf, int len, int slicelen, int flags) const
{
    char\* ptr = (char*)buf;
    int bytes_leavings = len;
    while(bytes_leavings > 0)
    {
        if(bytes_leavings > slicelen)
        {
            bytes_leavings -= this->send(ptr, slicelen, flags);
            ptr += slicelen;
        }
        else
        {
            bytes_leavings -= this->send(ptr, bytes_leavings, flags);
        }
    }
    return len - bytes_leavings;
}

what  happened when socket closed by remote?  how can this loop quit?

bug?

**Comment by halx99** [comment]
Yes, It's bug, I think this function is unnecessary, I will remove it.
