### ISSUE TITLE
How to determine the length of a string in a binary stream is 1 byte 2 bytes or 4 bytes？

### ISSUE THREAD

**Issue by EricDDK** [simdsoft/yasio#101]

**Comment by halx99** [comment]
Well, the ibstream, obstream doesn't determine the length field length, you should handle this by you self manually.

**Comment by EricDDK** [comment]
> Well, the ibstream, obstream doesn't determine the length field length, you should handle this by you self manually.

yasio::string_view ibstream_view::read_v() { return read_vx<uint32_t>(); }
yasio::string_view ibstream_view::read_v16() { return read_vx<uint16_t>(); }
yasio::string_view ibstream_view::read_v8() { return read_vx<uint8_t>(); }

In TCP binary, if I send a short string, I only need the first byte to define the length, but suppose I need to send a long string now, I need the first 2 bytes to define the length, then how to judge this is string defined by 1byte, 2bytes or 4 bytes when reading string?  I can't figure out here so that submit this issue.

**Comment by halx99** [comment]
That's need protocol to define,
such as
If the sender send follow data:
```c++
obstream obs;
obs.write_v8("hello1");
obs.write_v("hello2");
obs.write_v16("hello3");
```

then the receiver should read as same sequence:
```c++
ibstream_view ibs(buffer, len);
auto strV8 = ibs.read_v8();
auto strV32 = ibs.read_v();
auto strV16 = ibs.read_v16();
```

**Comment by EricDDK** [comment]
> That's need protocol to define,
> such as
> If the sender send follow data:
> 
> ```c++
> obstream obs;
> obs.write_v8("hello1");
> obs.write_v("hello2");
> obs.write_v16("hello3");
> ```
> 
> then the receiver should read as same sequence:
> 
> ```c++
> ibstream_view ibs(buffer, len);
> auto strV8 = ibs.read_v8();
> auto strV32 = ibs.read_v();
> auto strV16 = ibs.read_v16();
> ```

I read the C# doc then found that the BinaryRead class only have one method called ReadString(). Then I decompile .net framework.

``` C#
public virtual string ReadString()
{
    if (this.m_stream == null)
    {
        __Error.FileNotOpen();
    }
    int num = 0;
    int capacity = this.Read7BitEncodedInt();
    if (capacity < 0)
    {
        object[] values = new object[] { capacity };
        throw new IOException(Environment.GetResourceString("IO.IO_InvalidStringLen_Len", values));
    }
    if (capacity == 0)
    {
        return string.Empty;
    }
    if (this.m_charBytes == null)
    {
        this.m_charBytes = new byte[0x80];
    }
    if (this.m_charBuffer == null)
    {
        this.m_charBuffer = new char[this.m_maxCharsSize];
    }
    StringBuilder sb = null;
    do
    {
        int count = ((capacity - num) > 0x80) ? 0x80 : (capacity - num);
        int byteCount = this.m_stream.Read(this.m_charBytes, 0, count);
        if (byteCount == 0)
        {
            __Error.EndOfFile();
        }
        int length = this.m_decoder.GetChars(this.m_charBytes, 0, byteCount, this.m_charBuffer, 0);
        if ((num == 0) && (byteCount == capacity))
        {
            return new string(this.m_charBuffer, 0, length);
        }
        if (sb == null)
        {
            sb = StringBuilderCache.Acquire(capacity);
        }
        sb.Append(this.m_charBuffer, 0, length);
        num += byteCount;
    }
    while (num < capacity);
    return StringBuilderCache.GetStringAndRelease(sb);
}
```

I think that .net use this method.

``` C#
protected internal int Read7BitEncodedInt()
{
    byte num3;
    int num = 0;
    int num2 = 0;
    do
    {
        if (num2 == 0x23)
        {
            throw new FormatException(Environment.GetResourceString("Format_Bad7BitInt32"));
        }
        num3 = this.ReadByte();
        num |= (num3 & 0x7f) << num2;
        num2 += 7;
    }
    while ((num3 & 0x80) != 0);
    return num;
}
```
Although the game that I create doesn't need to pass long strings, I hope I can understand this problem.
Thanks for your reply.

**Comment by halx99** [comment]
Yes, the .net use variable length field to encode string

**Comment by halx99** [comment]
7f
8f 7f -- 7f 7f
8f 8f 7f -- 7f 7f 7f
8f 8f 8f 7f -- 7f 7f 7f 7f

**Comment by EricDDK** [comment]
> 7f
> 8f 7f -- 7f 7f
> 8f 8f 7f -- 7f 7f 7f
> 8f 8f 8f 7f -- 7f 7f 7f 7f

Thanks. 
I am so excited that I implemented it.
it use 7bits to describe. it's brilliant.

**Comment by halx99** [comment]
Great job
