### ISSUE TITLE
YOPT_TCP_KEEPALIVE与应用层心跳

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#117]
YOPT_TCP_KEEPALIVE设置了这个，还需要应用层心跳机制吗？

**Comment by halx99** [comment]
不必

**Comment by airx** [comment]
> 不必

这么厉害！这个与服务器无关吧？
我测试下，看设置了这个，什么都不做，tcp链接会不会一直在。

**Comment by halx99** [comment]
嗯，TCP协议层的，应用层无关，你可以这样测试：连接服务器成功后，直接拔掉网线，加入此参数设置如下:
```set_option(yasio.YOPT_TCP_KEEPALIVE, 30, 10, 2);```, 则会在30秒后发送第一个心跳包，无回应，间隔10s再发一个心跳包，无回应，则触发tcp连接断开

**Comment by airx** [comment]
> 嗯，TCP协议层的，应用层无关，你可以这样测试：连接服务器成功后，直接拔掉网线，加入此参数设置如下:
> `set_option(yasio.YOPT_TCP_KEEPALIVE, 30, 10, 2);`, 则会在30秒后发送第一个心跳包，无回应，间隔10s再发一个心跳包，无回应，则触发tcp连接断开

好的，真是非常感谢！

**Comment by halx99** [comment]
不客气
