### ISSUE TITLE
reconnect表现规律

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#118]
想跟你确认下reconnect的规律，我这边测试到的现象是：
如果设置了reconnect option，当连接建立成功（YEK_CONNECT_RESPONSE&&status==0）了，任何情况连接断开（YEK_CONNECTION_LOST），只会触发一次reconnect动作吧？
会衍生大概三个问题：
1、首次connect如果不成功(YEK_CONNECT_RESPONSE&&status!=0)，不会触发reconnect。
2、连接成功，意外断开，触发reconnect，如果连接不成功，不会再次触发reconnect。
3、连接成功，意外断开，触发reconnect，再次连接成功，又获得一次reconnect机会。
请确认下reconnect机制是这样的吗？

**Comment by halx99** [comment]
是的，reconnect的行为是针对已成功建立连接后断开的情况

**Comment by airx** [comment]
谢谢
