### ISSUE TITLE
YOPT_DEFER_EVENT及嵌套事件疑惑

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#120]
假设YOPT_DEFER_EVENT设为0，我直接上点代码，请你答疑下：
![image](https://user-images.githubusercontent.com/1214492/62828847-720ee700-bc22-11e9-8256-7e0694722de4.png)

如图的用法合理吗？或者有更好的用法建议吗？

**Comment by halx99** [comment]
如果设置为0，则网络事件会在io_service线程直接调度，如果设计到更新UI或OpenGL对象，你需要自己处理线程安全问题，通常不能直接在事件回调中更新界面

**Comment by halx99** [comment]
2. 不必手动调用

**Comment by airx** [comment]
> 如果设置为0，则网络事件会在io_service线程直接调度，如果设计到更新UI或OpenGL对象，你需要自己处理线程安全问题，通常不能直接在事件回调中更新界面

在io_service线程里，我不更新界面；只是在这个线程调度的事件中，我能像1那样，调用open等相关涉及io_service的操作吗？不会存在嵌套或者死锁情况吧。

**Comment by airx** [comment]
> 1. 不必手动调用

不用手动调？在释放或者程序要退出时，如果我要关掉yasio所有相关的，请问如何优雅关闭呢。

**Comment by halx99** [comment]
> > 如果设置为0，则网络事件会在io_service线程直接调度，如果设计到更新UI或OpenGL对象，你需要自己处理线程安全问题，通常不能直接在事件回调中更新界面
> 
> 在io_service线程里，我不更新界面；只是在这个线程调度的事件中，我能像1那样，调用open等相关涉及io_service的操作吗？不会存在嵌套或者死锁情况吧。

不会有嵌套死锁问题

**Comment by airx** [comment]
> > > 如果设置为0，则网络事件会在io_service线程直接调度，如果设计到更新UI或OpenGL对象，你需要自己处理线程安全问题，通常不能直接在事件回调中更新界面
> > 
> > 
> > 在io_service线程里，我不更新界面；只是在这个线程调度的事件中，我能像1那样，调用open等相关涉及io_service的操作吗？不会存在嵌套或者死锁情况吧。
> 
> 不会有嵌套死锁问题

OK，谢谢

**Comment by halx99** [comment]
> > 1. 不必手动调用
> 
> 不用手动调？在释放或者程序要退出时，如果我要关掉yasio所有相关的，请问如何优雅关闭呢。

service析构会自动释放资源，另外收到CONNECTION_LOST,说明连接已经关闭，不必重复调用close
