### ISSUE TITLE
YOPT_LFBFD_PARAMS疑问

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#121]
代码如图
![image](https://user-images.githubusercontent.com/1214492/62851568-2a1ebb80-bd19-11e9-9d59-28da9fa0f6ec.png)
这样的话，YOPT_LFBFD_PARAMS这个参数会对udp也产生作用了？实测貌似是这样。
udp本身就是一个个的包，并不需要YOPT_LFBFD_PARAMS呀。
怎么办呢？

**Comment by airx** [comment]
主要是想在一个service里面做多个连接，并且对tcp使用YOPT_LFBFD_PARAMS，省心；而udp或者其他的不使用YOPT_LFBFD_PARAMS。

**Comment by airx** [comment]
嗯，改了下源码，lfb_我变成了数组，YOPT_LFBFD_PARAMS第一个参数是channel_index:
service->set_option(YOPT_LFBFD_PARAMS, 0, 65535, 0, 4, 0); //tcp
service->set_option(YOPT_LFBFD_PARAMS, 1, 65535, -1, 0, 0); //udp
以及相关的__builtin_decode_len多加一个参数channel_index，搞定。
LZ看需不需要更新下YOPT_LFBFD_PARAMS这个参数的用法，多加一个channel_index，粒度更细点。

**Comment by halx99** [comment]
> 嗯，改了下源码，lfb_我变成了数组，YOPT_LFBFD_PARAMS第一个参数是channel_index:
> service->set_option(YOPT_LFBFD_PARAMS, 0, 65535, 0, 4, 0); //tcp
> service->set_option(YOPT_LFBFD_PARAMS, 1, 65535, -1, 0, 0); //udp
> 以及相关的__builtin_decode_len多加一个参数channel_index。

对，可以的，全局改为channel相关

**Comment by airx** [comment]
建议YOPT_LFBFD_PARAMS这个option，需要传入channel_index比较好，不同channel给区分开。

**Comment by halx99** [comment]
好的

**Comment by halx99** [comment]
@airx 已优化为channel关联

**Comment by airx** [comment]
> @airx 已优化为channel关联

收到，3Q！
