### ISSUE TITLE
transport的send后需要flush吗？

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#122]
感觉好像调用了send，有时并没有立即发送，而是跟下次或下下次一起发的。
如果想立即发送，是send后调用flush？max_wait_duration这个是什么意思，flush要阻塞？

**Comment by airx** [comment]
貌似service的write方法好用点，立即发出去了，行为已知。

**Comment by halx99** [comment]
你是说调用io_service的write接口吧，这个是异步的，真正发送在service线程的事件循环

**Comment by halx99** [comment]
对，这个库，一般都是直接用service的write接口

**Comment by halx99** [comment]
transport的send,flush是内部使用的，已经标记为```protect```权限: https://github.com/halx99/yasio/commit/23f5b01cd86a6c16c84fe0430be355b09138d6bb

**Comment by airx** [comment]
> transport的send,flush是内部使用的，已经标记为`protect`权限: [23f5b01](https://github.com/halx99/yasio/commit/23f5b01cd86a6c16c84fe0430be355b09138d6bb)

谢谢，这样对于使用者少了一份疑惑。多一个选择多一份疑惑~
