### ISSUE TITLE
UDP发包容易出现lost: Operation not permitted

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#126]
UDP持续发包（20ms发一次），同时也在接收。发送量也不大，每次几十字节的样子。小米6手机会出现这个问题，跑一会必现lost connection，是什么原因呢：
[yasio][1565921628662591] [index: 1] the connection #72 is lost, offset:-1, ec:1, detail:Operation not permitted
[yasio][1565921628692946] [transport: 0x7e540e79c0] send failed, the connection not ok!

目前我在排查是哪个步骤导致的lost，感觉像是发送造成的

**Comment by airx** [comment]
当然udp同时也在接收

**Comment by airx** [comment]
如果不好一下解决，是否可以提供udp不connect，配上地址发送的接口呢

**Comment by airx** [comment]
小米6手机会出现这个问题

**Comment by airx** [comment]
重现出来了，还有华为等手机，屏幕一熄，就出现udp这个问题了，tcp是仍然正常的。

**Comment by halx99** [comment]
好的，我研究研究咋回事

**Comment by halx99** [comment]
你是用的```YCM_UDP_CLIENT```吗?

**Comment by airx** [comment]
> 你是用的`YCM_UDP_CLIENT`吗?

是的，UDP_CLIENT

**Comment by airx** [comment]
> 好的，我研究研究咋回事

正在魔改，加上一个sendto接口直接使用看看会不会有发送错误，如果可行的话，建议给udp加一个sendto接口

**Comment by halx99** [comment]
找到偏文章: https://blog.csdn.net/EthanCo/article/details/53219084
貌似和sendto可能没关系

**Comment by airx** [comment]
> 找到偏文章: https://blog.csdn.net/EthanCo/article/details/53219084
> 貌似和sendto可能没关系

改你的变动有点大，改了个sendto出来，不过不能完全说明问题，我怀疑是udp connect机制问题，之前我自己select socket好像没出这个状况。
我先做个实验吧，udp socket监听接收和sendto，如果息屏没问题的话，麻烦你对udp增加一个非open（connect）机制，和sendto接口吧。

**Comment by halx99** [comment]
```
1) You cannot rely on the kernel blocking in the sendto system call.
While this might happen, you cannot rely on it. For example, if the
packets are overloading a link that is not directly connected to this
computer, there is no way for the kernel to know.

2) If you don't like the EPERM error, ignore it. The kernel is trying
to be nice and telling you that your packet wasn't sent because, by
sheer luck, it happens to know this. If this confuses you or causes
you problems, fine, pretend you don't know it. The kernel is not
required to tell you there's a problem, so pretend it didn't if
finding out bothers you.

Again, you *MUST* implement transmit pacing. Simply blasting an
arbitrarily large amount of packets over a link in an arbitrarily
small amount of time is anti-social and may disrupt whatever else is
going on with that link. The kernel is entirely right to refuse to
permit you to behave that way.

You must use some kind of feedback loop to determine how rapidly to
send packets and back off when packets get dropped. UDP does not
provide transmit pacing like TCP does -- it is the application's
responsibility.
```

**Comment by airx** [comment]
验证了下面这样是OK的。
接收：udp bind, recvfrom；
发送：sendto。
不会存在息屏影响。

**Comment by airx** [comment]
我自己用了一个thread搞接收，connect recv&recvfrome和send，sendto都试过了，也没问题。发现怎么都是正常的。
难道是yasio的bug？

**Comment by halx99** [comment]
你也是用的非阻塞模式，sendto, 有判断返回值以及errno吗？

**Comment by airx** [comment]
> 你也是用的非阻塞模式，sendto, 有判断返回值以及errno吗？

哦，我用的阻塞模式，返回值都是正常的，recv(recvfrom)和send(sendto)，返回值都是大于0的。
我再用非阻塞的试下。不过都是直接接收，没用select这些。
我之前一个版本用了select，也没出问题。

**Comment by halx99** [comment]
EPERM是errno返回的

**Comment by airx** [comment]
非阻塞模式也试了，send一直正常。recv如果返回-1，errno是EAGAIN，也是正常的。
应该基本可以确认是yasio对udp这里哪有点问题。

**Comment by halx99** [comment]
好的，回头我用小米手机试试

**Comment by halx99** [comment]
每隔20秒发几十个字节UDP包，对吧

**Comment by airx** [comment]
可能跟发送频次没关系，就是息屏会触发udp connection lost。
我用的service本身的网络调度线程。一个tcp和一个udp client连接。

**Comment by halx99** [comment]
OK

**Comment by airx** [comment]
我之前是自己手写select，监听一个tcp和udp socket，也没有这种错误，只是我手写的比较麻麻杂杂，结构不太清晰，所以打算换成yasio来。
所以可能是udp socket那，不是错误，被当成错误，然后触发了lost事件，close了后，再send应该就是Operation not permitted了？

**Comment by halx99** [comment]
close之后应该报这个错: send failed, the connection not ok!

**Comment by halx99** [comment]
我测试一下忽略EPERM这个异常试试，息屏恢复后能否发包

**Comment by halx99** [comment]
你自己写的，息屏后继续发包，另一端能收到UDP消息吗？

**Comment by airx** [comment]
> 你自己写的，息屏后继续发包，另一端能收到UDP消息吗？

可以，接收发送都是正常的

**Comment by halx99** [comment]
你是这样使用的吗？
```cpp
auto yss = yasio_shared_service;
    io_hostent host = {"mirror.x-studio365.com", 50001};
    yss->start_service(&host, [=](event_ptr ev){
        if(ev->kind() == YEK_CONNECT_RESPONSE) {
            if(ev->status() == 0) {
                cocos2d::log("%s", "yasio: open udp channel succeed");
                auto transport = ev->transport();
                yss->schedule(std::chrono::microseconds(300), [=](bool cancelled){
                    static int counter = 0;
                    char message[128];
                    sprintf(message, "UECHOMSG#%d", ++counter);
                    yss->write(transport, std::vector<char>(message, message + strlen(message)));
                }, true);
            }
        }
        if(ev->kind() == YEK_PACKET){
            auto packet = std::move(ev->packet());
            packet.push_back('\0');
            cocos2d::log("yasio: receive from peer: %s", packet.data());
        }
    });

    yss->set_option(YOPT_DEFER_EVENT, 0);

    utils::findChild<ui::Button*>(ui, "btn_startTest")->addClickEventListener([=](cocos2d::Ref*){
        yss->open(0, YCM_UDP_CLIENT);
    });
```

**Comment by halx99** [comment]
这里我设置的300微秒发送udp包，小米mix2s测试，貌似没出现
当我设置成20微妙， 则很容易出现

**Comment by halx99** [comment]
不知道你那边具体设置的是多少呢？
是20毫秒: ```std::chrono::milliseconds(20)```还是20微妙: ```std::chrono::microseconds(20)```呢?

**Comment by halx99** [comment]
小米mix2s测试结论如下:
发送频率过快，20微秒， 必然出现异常，EPERM: Operation not permitted
且可以简单忽略，socket句柄始终是有效的，也印证了: https://blog.csdn.net/EthanCo/article/details/53219084 这篇文章的说法

**Comment by halx99** [comment]
更新一下最新代码，再试试
