### ISSUE TITLE
手机切网问题

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#129]
TCP情况：
1、数据:ON，WLAN:ON，此时用的WLAN，tcp_con_1;
2、手动关掉WLAN，会触发yasio lost，但服务器不会触发tcp_con_1 disconnect（类似拔网线），此时用数据重连成功, tcp_con_2;
3、打开WLAN，又会触发yasio lost, 此时用的WLAN再重连，tcp_con_3;
4、服务器此时关掉tcp_con_2, 会触发正常的tcp_con_3也关了--->问题！

**Comment by airx** [comment]
出错了触发lost前，close这个socket了吗？

**Comment by airx** [comment]
我再试一试

**Comment by halx99** [comment]
任何时候，出现lost, 都会close socket
