### ISSUE TITLE
mac解析域名失败

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#133]
[yasio]getipsv_internal: endpoint=127.0.0.1:0
[yasio]getipsv_internal: endpoint=[::]:0
[yasio]getipsv_internal: endpoint=[fe80::]:0
[yasio]getipsv_internal: endpoint=[fe80::c7b:619e:45bd:b92]:0
[yasio]getipsv_internal: endpoint=10.0.0.42:0
[yasio]getipsv_internal: endpoint=[fe80::b85e:daff:feb4:232]:0
[yasio]getipsv_internal: endpoint=[fe80::3bed:ba2c:4467:786]:0
[yasio]getipsv_internal: endpoint=[fe80::d732:295c:c0d7:2f9]:0
[yasio]getipsv_internal: flags=1, ifa_count=8
[yasio][1567008383384834][index: 0] resolving domain name: www.baidu.com
[yasio][1567008383384888][index: 0] getaddrinfo failed, ec:-1, detail:Unknown error
[yasio][1567008383384985][index: 0] connect server www.baidu.com:9010 failed, ec:-498, detail:Resolve host failed!

**Comment by halx99** [comment]
浏览器能打开吗？

**Comment by halx99** [comment]
是在设备上跑的吗？

**Comment by airx** [comment]
mac上跑的，上网正常

**Comment by halx99** [comment]
还是说直接在mac上跑的？

**Comment by airx** [comment]
int io_service::__builtin_resolv(std::vector<ip::endpoint> &endpoints, const char *hostname,
                                 unsigned short port)
{
//  if (this->ipsv_ & ipsv_ipv4)
	return xxsocket::resolve_v4(endpoints, hostname, port);
//  else if (this->ipsv_ & ipsv_ipv6) // localhost is IPV6 ONLY network
//    return xxsocket::resolve_v6(endpoints, hostname, port) != 0
//               ? xxsocket::resolve_v4to6(endpoints, hostname, port)
//               : 0;
//  return -1;
}
注释成这样就正常

**Comment by halx99** [comment]
看你打印，检测的也应该是ipv4啊

**Comment by halx99** [comment]
应该走第一个分支，也就是xxsocket::resolve_v4(endpoints, hostname, port);
应该没啥区别才对

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/63873816-d982b000-c9f2-11e9-97db-d2d3649b9c9e.png)
在这里打个断点看看

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/63873921-151d7a00-c9f3-11e9-9902-43f2ef4cf01a.png)
还有这里，看看this->ipsv_的值

**Comment by airx** [comment]
![Snipaste_2019-08-29_00-21-59](https://user-images.githubusercontent.com/1214492/63874020-45fdaf00-c9f3-11e9-8823-20d4be3a4c74.jpg)

**Comment by airx** [comment]
> ![image](https://user-images.githubusercontent.com/6977319/63873921-151d7a00-c9f3-11e9-9902-43f2ef4cf01a.png)
> 还有这里，看看this->ipsv_的值

0，直接到-1了

**Comment by halx99** [comment]
晕，网络线程函数开始位置会调用一次，看看呢？

**Comment by halx99** [comment]
![Screenshot_2019-08-29-00-27-40-475_com microsoft emmx](https://user-images.githubusercontent.com/6977319/63874392-05526580-c9f4-11e9-807a-7c02e01ac938.png)

**Comment by airx** [comment]
this->ipsv_ = xxsocket::getipsv();
这里ipsv_得到是1

**Comment by halx99** [comment]
那就怪了，代码里，只有ipsv_是-1才会再次去获取，一旦>0, 就不会再去获取了

**Comment by airx** [comment]
![Snipaste_2019-08-29_00-35-53](https://user-images.githubusercontent.com/1214492/63874931-0a63e480-c9f5-11e9-8678-6c91812ee59f.jpg)
初始化设置时，注释这里就对了

**Comment by airx** [comment]
> ![Snipaste_2019-08-29_00-35-53](https://user-images.githubusercontent.com/1214492/63874931-0a63e480-c9f5-11e9-8678-6c91812ee59f.jpg)
> 初始化设置时，注释这里就对了

但我这里好像是抄的你的示例代码呀

**Comment by airx** [comment]
> > ![Snipaste_2019-08-29_00-35-53](https://user-images.githubusercontent.com/1214492/63874931-0a63e480-c9f5-11e9-8678-6c91812ee59f.jpg)
> > 初始化设置时，注释这里就对了
> 
> 但我这里好像是抄的你的示例代码呀

cpptest.cpp,抄的62-66行，多设置下就有这个bug呢

**Comment by halx99** [comment]
servvice不是同一个吧

**Comment by halx99** [comment]
你io_service是不是用的单利

**Comment by airx** [comment]
> 你io_service是不是用的单利

倒没专门用单例，但我就一个ios_service对象呀

**Comment by halx99** [comment]
那要注意生命周期

**Comment by halx99** [comment]
你这里lambda表达是参数捕获也有点问题

**Comment by halx99** [comment]
既然已经取到指针又何必引用传递，这样反而有问题

**Comment by airx** [comment]
> 你这里lambda表达是参数捕获也有点问题
果然是这个问题！
C++细节不精啊，汗颜~~

**Comment by halx99** [comment]
嗯，明确指针和引用的真谛，以后就不会采坑了，加油
