### ISSUE TITLE
udp_client接口增强一点

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#134]
1、udp_client open操作就connect了，能否参数指明可以不connect，只监听接收呢？
2、如果1成立，udp_client发送需要一个类似sendto的接口，指明地址。
3、当然监听接收时，也要有发送者的地址了。
---------------------------------------------------------------------------------------
问题缘由还是发现在华为小米等手机上有电源管理，当程序息屏或者退到后台时，udp socket可以接收，但不能发送了，发送就是之前说的EPERM错误。
我在想是不是跟udp connect机制相关，sendto是可以的。

**Comment by halx99** [comment]
你确定sendto不会? 我的测试结果是小米mix2s 切到后台会短暂出现EPERM, 但持续发送UDP数据包，之后就又恢复，能正常发送。

**Comment by airx** [comment]
> 你确定sendto不会? 我的测试结果是小米mix2s 切到后台会短暂出现EPERM, 但持续发送UDP数据包，之后就又恢复，能正常发送。

我再确认确认

**Comment by halx99** [comment]
怎么样，确认的如何了?

**Comment by airx** [comment]
> 怎么样，确认的如何了?

还有其他问题解决，这个还没时间确认，可以先close了，这两天确认了我再给你反馈吧。
