### ISSUE TITLE
“io_transport_base”: 未声明的标识符

### ISSUE THREAD

**Issue by xboy2006** [simdsoft/yasio#135]
引擎：cocos creator 2.0.9
想在cocoscreator中使用udp。但是编译遇到了问题。

使用vs2017进行编译。WinSDk：10.0.17134.0

IDE显示如下错误：
1>------ 已启动生成: 项目: libcocos2d, 配置: Debug Win32 ------
1>yasio_jsb20.cpp
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(970): error C2065: “io_transport_base”: 未声明的标识符
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(970): error C2672: “JSBClassType::registerClass”: 未找到匹配的重载函数
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(970): error C2974: 'JSBClassType::registerClass' : 模板 对于 'T'是无效参数，应为类型
1>f:\work\cocos\cocos2d-x-lite\cocos\scripting\js-bindings\manual\jsb_classtype.hpp(39): note: 参见“JSBClassType::registerClass”的声明
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(1053): error C2065: “io_transport_base”: 未声明的标识符
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(1053): error C2672: “native_ptr_to_seval”: 未找到匹配的重载函数
1>f:\work\cocos\cocos2d-x-lite\external\sources\yasio\impl\yasio_jsb20.cpp(1053): error C2974: 'native_ptr_to_seval' : 模板 对于 'T'是无效参数，应为类型
1>f:\work\cocos\cocos2d-x-lite\cocos\scripting\js-bindings\manual\jsb_conversions.hpp(509): note: 参见“native_ptr_to_seval”的声明
1>已完成生成项目“libcocos2d.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

大概搜了下，没收到io_transport_base相关的信息。

**Comment by halx99** [comment]
更新最新master再试试
