### ISSUE TITLE
YASIO_DISABLE_SPSC_QUEUE 的意义是什么

### ISSUE THREAD

**Issue by atmgnd** [simdsoft/yasio#152]
# 版本
Revision: 5f685cf62260c34967f2fc771eaa1b20c3968922
Author: halx99 <halx99@live.com>
Date: 10/26/2019 6:13:55 PM
Message:
Fix CMake optimization for msvc debug.

# 环境
visual studio 2017， 修改test/cpptest

# 问题
你好，我看到最近的修改中使用了单消费者单生产者无锁队列。但根据我的测试，此修改似乎会导致崩溃。
1. 我在测试代码中在，YEK_CONNECT_RESPONSE处新开了一个线程一直写。运行几秒后，会产生随机崩溃。
测试用例见：附件中的“1 默认单消费者单生产者无锁队列 崩溃”

2. 如果我在相同的地方添加一把锁，并开4个线程。则无论是否定义YASIO_DISABLE_SPSC_QUEUE都会导致崩溃。
测试用例见：附件中的“2 加锁多线程写 崩溃”
回退至以下版本则用例1，2均未见崩溃
Revision: c1615993d13738ba0a9a2efe05bd813a9a50cbc1
Author: halx99 <halx99@live.com>
Date: 10/24/2019 9:37:54 PM
Message:
Fix ci warnings.

3. 定义YASIO_DISABLE_SPSC_QUEUE的意义是什么呢？
是否原意定义YASIO_DISABLE_SPSC_QUEUE后多线程写就不需要使用者加锁了呢？如果不是，那么YASIO_DISABLE_SPSC_QUEUE的意图是什么？**感觉这个修改改变了api的原始行为，破坏了前后兼容性**。

# 测试用例
[测试用例.zip](https://github.com/halx99/yasio/files/3775714/default.zip)

**Comment by atmgnd** [comment]
复现方法为先运行服务“cpptest.exe 11”（有参数则会是运行tcp server）
再无参数运行（客户端） cpptest.ext

**Comment by atmgnd** [comment]
没有问题了，是我发送太快了，内存用完了。。。

**Comment by halx99** [comment]
@atmgnd 确定是内存耗尽造成的吗，我看你前面说，回滚到版本： https://github.com/halx99/yasio/commit/c1615993d13738ba0a9a2efe05bd813a9a50cbc1
没问题

**Comment by atmgnd** [comment]
@halx99 确实是，回退测试时没有仔细测（相比测试最新的代码），问题是我测试代码里写数据的地方没有任何停顿，发送队列太大，时间一久内存就不够了， 测试时发慢点就好了。

我也是近几天要写网络相关的程序， 才无意看到这个库的， 网络交互好久不了。

小巧好用的库，很赞。

**Comment by halx99** [comment]
@atmgnd 好的，感谢反馈
