### ISSUE TITLE
主备连接需求

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#166]
假设我服务有两套或多套（高可用），我想yasio作为TCP客户端，首先去连主服务的IP，只有主服务连接失败才连接备用服务IP，依次进行下去。
yasio这种回调形式，好像实现这么一个功能有点复杂，代码到处跑。
有原生支持这种形式吗？假设不支持，yasio怎么使用比较优雅一点啊。

**Comment by halx99** [comment]
伪代码, 在连接失败回调里:
 if(ip == "主ip) {
   service.set_option(YOPT_C_REMOTE_ENDPOINT, channel_index, "备用IP", 2051/*备用端口*/)
   service.open(channel_index, YCM_TCP_CLIENT); // 再次发起连接请求
 }

**Comment by airx** [comment]
谢谢，这样好像也行。
service.set_option(YOPT_DEFER_EVENT, 0); // 禁用事件队列，网络事件直接在服务线程分派
不过假设我设置了这个，在回调里面直接open就要出问题了。

**Comment by halx99** [comment]
不会

**Comment by halx99** [comment]
连接始终是队列，会在线程服务循环的下次tick处理

**Comment by airx** [comment]
~~~c++
int main() {
	yasio::inet::io_hostent endpoints[] = {
		{"127.0.0.1", 8010}  // tcp client
	};
	io_service service;
	int retry_count = 0;
	service.start_service(endpoints, [&](event_ptr event) {
		switch (event->kind()) {
			case YEK_CONNECT_RESPONSE: {
				printf("The connection is YEK_CONNECT_RESPONSE, status=%d, %llu\n",
				       event->status(),
				       event->timestamp());
				if (event->status() != 0) {
					if (retry_count++ < 2) {
//						service.schedule(std::chrono::milliseconds (100), [&](bool cancelled){
						service.set_option(YOPT_C_REMOTE_ENDPOINT, 0, "127.0.0.1", 9010);
						service.open(0, YCM_TCP_CLIENT); // open tcp client
//						});
					} else
						exit(-1);
				}
				break;
			}
		}
	});
	service.set_option(YOPT_S_TIMEOUTS, 5,5,-1);
	service.set_option(YOPT_C_LFBFD_PARAMS, 0, 65535, 0, 4, 0);
	service.set_option(YOPT_S_DEFERRED_EVENT, 0); // 禁用事件队列，网络事件直接在服务线程分派
	service.open(0, YCM_TCP_CLIENT); // open tcp client

	getchar();
	return 0;
}
~~~
如果打开注释，用schedule，正常；如果没用schedule，直接open，无效。

**Comment by halx99** [comment]
好，我看看

**Comment by halx99** [comment]
应该是直接通知连接失败事件是的模式，信道处于YCS_OPENING状态，所以逻辑上禁止了open

**Comment by halx99** [comment]
我这边直接拷贝你的程序，跑了下，没毛病啊，用新IP重试了两次
![image](https://user-images.githubusercontent.com/6977319/70018424-f7971800-15c0-11ea-92c4-d116f4c481ca.png)

**Comment by airx** [comment]
<img width="781" alt="图片" src="https://user-images.githubusercontent.com/1214492/70019355-f3b8c500-15c3-11ea-837e-48e3c8755023.png">
open在回调里就没起作用，我是mac

**Comment by airx** [comment]
<img width="784" alt="图片" src="https://user-images.githubusercontent.com/1214492/70019636-e3551a00-15c4-11ea-88c6-9a0643df8356.png">
用schedule就正常

**Comment by halx99** [comment]
这里确实有点奇怪

**Comment by halx99** [comment]
win32: connect failed detected by timer
linux: connect failed detected at: do_nonblocking_connect_completion, sockerror=111

**Comment by halx99** [comment]
在非win32平台，就会触发这里检查重复连接
![image](https://user-images.githubusercontent.com/6977319/70023095-4e0c5280-15d1-11ea-89fa-1ee6e8e4d642.png)

**Comment by airx** [comment]
这算个bug？

**Comment by halx99** [comment]
拉取一下最新master提交试试

**Comment by airx** [comment]
嗯，对了，谢谢。
另外我现在正式在用的应该是你9月份的版本，不知道最近这段时间由什么变化，主要是稳定性bug上面

**Comment by halx99** [comment]
对，主要是稳定性，组播支持

**Comment by airx** [comment]
另外问个问题，有考虑udp send，可以加个sendto接口嘛？现在统一成tcp的形式只能send有点不方便。

**Comment by halx99** [comment]
这个没想好怎么加，目前接口上类似文件: open,write,close

**Comment by airx** [comment]
就类似这种呗，可以多几个参数重载形式
![image](https://user-images.githubusercontent.com/1214492/70027381-fb389800-15dc-11ea-81a1-e5f874aa2b03.png)
![image](https://user-images.githubusercontent.com/1214492/70027468-31761780-15dd-11ea-9cba-dae7ff7e030a.png)

**Comment by halx99** [comment]
你自己已经加好了？

**Comment by airx** [comment]
> 你自己已经加好了？

没有，就给UDP暴露类似sendto的接口即可。
这个要把地址参数传过去，我没完全理解你的写法，没太敢动~
希望作者亲自操刀比较好 ：）
UDP的需求是存在的，而且我们自己修改了，后面跟你主代码不太好同步，就飘离了

**Comment by halx99** [comment]
好，后面看看

**Comment by halx99** [comment]
需要sendto主要是出于什么原因呢，因为现在设计上，UDP通讯，会绑定4元组，然后直接用send也可以发UDP包

**Comment by airx** [comment]
> 需要sendto主要是出于什么原因呢，因为现在设计上，UDP通讯，会绑定4元组，然后直接用send也可以发UDP包

1、偶尔会发多个地址的情况，connect绑定了使用不是太灵活；
2、之前有手机熄屏造成udp connect失效（当然这个隐形bug一直还没时间真正来排查），用send发送失败的原因。所以想用sendto应该就没这个问题。

**Comment by halx99** [comment]
@airx 试试吧: https://github.com/simdsoft/yasio/pull/167

**Comment by airx** [comment]
> ```c++
> int main() {
> 	yasio::inet::io_hostent endpoints[] = {
> 		{"127.0.0.1", 8010}  // tcp client
> 	};
> 	io_service service;
> 	int retry_count = 0;
> 	service.start_service(endpoints, [&](event_ptr event) {
> 		switch (event->kind()) {
> 			case YEK_CONNECT_RESPONSE: {
> 				printf("The connection is YEK_CONNECT_RESPONSE, status=%d, %llu\n",
> 				       event->status(),
> 				       event->timestamp());
> 				if (event->status() != 0) {
> 					if (retry_count++ < 2) {
> //						service.schedule(std::chrono::milliseconds (100), [&](bool cancelled){
> 						service.set_option(YOPT_C_REMOTE_ENDPOINT, 0, "127.0.0.1", 9010);
> 						service.open(0, YCM_TCP_CLIENT); // open tcp client
> //						});
> 					} else
> 						exit(-1);
> 				}
> 				break;
> 			}
> 		}
> 	});
> 	service.set_option(YOPT_S_TIMEOUTS, 5,5,-1);
> 	service.set_option(YOPT_C_LFBFD_PARAMS, 0, 65535, 0, 4, 0);
> 	service.set_option(YOPT_S_DEFERRED_EVENT, 0); // 禁用事件队列，网络事件直接在服务线程分派
> 	service.open(0, YCM_TCP_CLIENT); // open tcp client
> 
> 	getchar();
> 	return 0;
> }
> ```
> 
> 如果打开注释，用schedule，正常；如果没用schedule，直接open，无效。

现在最新的版本，貌似这样操作不行了啊。构造函数就传了地址，有点麻烦了。

**Comment by halx99** [comment]
嗯，新版本，channel的初始化放到了构造函数，这样任何选项都可以在start_service之前设置
