### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by PatriceJiang** [simdsoft/yasio#168]
目前支持 SSL 吗？

**Comment by halx99** [comment]
目前只支持传输和协议拆包，不支持ssl, 我们使用的时候是在业务测将协议PDU进行加密处理，再调用框架发送，我们协议头没加密。

另外由于框架拆包是支持回调的，所以，即使需要加密协议头，也是可以的

**Comment by halx99** [comment]
最近尝试实现了下ssl: https://github.com/simdsoft/yasio/pull/177
前测试用例ssltest可以访问https://www.baidu.com
ca证书取自curl官网，访问常规https网站应该也没问题

另外还处于Draft阶段，一些细节尚需完善
