### ISSUE TITLE
沾包问题

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#178]
设置：
service->set_option(YOPT_CHANNEL_LFBFD_PARAMS, 0, 65535, 0, 4, 0); //tcp
![image](https://user-images.githubusercontent.com/1214492/70607972-56503780-1c3a-11ea-90b0-fb8b1d1aad0b.png)
有时会这样：
![image](https://user-images.githubusercontent.com/1214492/70607996-62d49000-1c3a-11ea-8313-fc475cc43ba8.png)

刚刚测出来的，这几个月的新版有fix这个问题吗

**Comment by airx** [comment]
我以为设置了set_option(YOPT_CHANNEL_LFBFD_PARAMS, 0, 65535, 0, 4, 0); //tcp
回调里面出来的packet就是分好了的，结果有沾包的可能性，那就比较严重呢。

**Comment by halx99** [comment]
正常是的，你们协议将包的前4个字节作为包长度吗？

**Comment by airx** [comment]
是啊，前4个字节作为包长度，所以客户端设置了这句：
set_option(YOPT_CHANNEL_LFBFD_PARAMS, 0, 65535, 0, 4, 0); 
就出现了偶发沾包现象，服务端发的两个包，119和104长度，结果YEK_PACKET回调里，packet是一个223的包，两个包和一起了，你看我发的截图，证明我两个包的内容是没问题的。

**Comment by airx** [comment]
按你的介绍说，应该是两次packet事件才对。
这个是偶发现象，但这个问题蛮严重，影响协议解析了。

**Comment by halx99** [comment]
有重现用例吗？

**Comment by halx99** [comment]
例如，故意合并两个包一起发送

**Comment by airx** [comment]
偶发的，即使合并两个包一起发，只要每个包头部字节标识对了，也不应该出现解析错误呀。

**Comment by halx99** [comment]
是的，就是看这种情况能否复现问题

**Comment by airx** [comment]
![image](https://user-images.githubusercontent.com/1214492/70609772-56056b80-1c3d-11ea-8b3f-c3905ca05c84.png)
![image](https://user-images.githubusercontent.com/1214492/70609797-64ec1e00-1c3d-11ea-95c5-bd796ee37218.png)
抓包和程序里打印，两个包都是对的，但yasio出现把这两个包合并给回调出去了

**Comment by halx99** [comment]
意思是可以重现？

**Comment by halx99** [comment]
我写个测试用例试试

**Comment by airx** [comment]
你试试，用本机对本机

**Comment by halx99** [comment]
另外你目前用的是哪个release版本

**Comment by airx** [comment]
感觉版本比较早了，估计是9月份的。
主要你改了代码，有时要变接口或者命名，我就没跟着升级。

**Comment by airx** [comment]
![image](https://user-images.githubusercontent.com/1214492/70611161-b3022100-1c3f-11ea-806e-31a6f4a36a9f.png)
用debug看了下，供你参考。
按正常来说，虽然一下收到了223的buffer，这里decode_len_应该解析出来是119才对吧，结果是223，是不是这里出问题了？

**Comment by airx** [comment]
问题找到了，length_field_offset是-1了。
![image](https://user-images.githubusercontent.com/1214492/70611706-931f2d00-1c40-11ea-9aa1-c577e0184cab.png)
但设置的是0啊:
![image](https://user-images.githubusercontent.com/1214492/70611740-a3cfa300-1c40-11ea-874b-e4b3f6648804.png)

**Comment by halx99** [comment]
写了个拆包测试用例，你看看，我这边打印正常，另外注意： 设置拆包参数要在start_service之后

**Comment by airx** [comment]
> 写了个拆包测试用例，你看看，我这边打印正常，另外注意： 设置拆包参数要在start_service之后

汗，我写在前面的！怪不得没设置上。哪些要在前面设置，哪些要在后面设置，感觉你文档要写清楚一点。。。
以前没出错，可能有时是天然分包就没出错，现在出错是本机传输太快了。

**Comment by airx** [comment]
![image](https://user-images.githubusercontent.com/1214492/70612810-96b3b380-1c42-11ea-9d01-975b6f4bbfea.png)
麻烦你看下，哪些应该写后面，哪些写前面

**Comment by halx99** [comment]
新版本里宏清楚些，_S_卸载前， _C_都在后

**Comment by halx99** [comment]
你的截图里channel相关的全放到后面

**Comment by halx99** [comment]
我后面补一下文档

**Comment by airx** [comment]
![image](https://user-images.githubusercontent.com/1214492/70617323-4bea6980-1c4b-11ea-9d3a-be06ede00ec1.png)
这是netty的，建议再加个这个参数。
另外是否有类似的编码器？

**Comment by halx99** [comment]
嗯嗯，这个就是借鉴了netty的，编码器你参考我提交的测试用例 issue178 obstream

**Comment by airx** [comment]
yasio差一个initialBytesToStrip参数，这样得到包可以不含长度字段。

**Comment by halx99** [comment]
如果长度域不在首4个字节呢，或者包头有需要的信息呢？

**Comment by airx** [comment]
initialBytesToStrip为0即可。
yasio有netty的其他几个参数，差一个initialBytesToStrip功能。
现在yasio是把包全部解弄出来了，长度字段其实可以不要，所以可以用initialBytesToStrip控制要不要，更方便点。
netty它所有参数还是有道理的哈。

**Comment by halx99** [comment]
ok

**Comment by halx99** [comment]
See also #182

**Comment by halx99** [comment]
@airx 分支ibts已实现initialBytesToStrip参数，默认0，分支地址: https://github.com/simdsoft/yasio/tree/ibts
也可以访问PR: https://github.com/simdsoft/yasio/pull/187 查看变化

**Comment by airx** [comment]
好的，谢谢
