### ISSUE TITLE
Jsb20  js_yasio_io_service_start_service  Error

### ISSUE THREAD

**Issue by superlixun** [simdsoft/yasio#192]
- js_yasio_io_service_start_service 中判断参数个数的地方还是2，但是js example 和C++代码中都是一个cb

- 手动改了参数个数为1之后，设置cb Android真机 跑 js example 报错 jsb-default/frameworks/cocos2d-x/cocos/scripting/js-bindings/jswrapper/Value.cpp:539: se::Object *se::Value::toObject() const: assertion "isObject()"

**Comment by halx99** [comment]
好，我看看

**Comment by halx99** [comment]
@superlixun 更新一下v3.30分支最新提交，应该没问题了， 有其他问题，随时反馈

**Comment by superlixun** [comment]
@halx99 这个好了 ，但是还有一个问题

- yclient.open(0,  yasio.YCM_KCP_CLIENT); 这样写的话 报错  Value.cpp:477: double se::Value::toNumber() const: assertion "_type == Type::Number || _type == Type::Boolean" failed
这样写 yclient.open(0,  81);  就行。
先写这里吧，你看不见的话再新建 issues

**Comment by halx99** [comment]
KCP没导出，你是要用KCP?

**Comment by halx99** [comment]
@superlixun
KCP你c++要在yasio/detail/config.hpp开启编译，不然你传了也没kcp的Transport实现，也就没功能

**Comment by superlixun** [comment]
@halx99  看你的文档了，  解开这行的注释对吧 // #define YASIO_HAVE_KCP 1，并且下载 ikcp 的文件放kcp 文件夹，都做了。我把yasio.YCM_KCP_CLIENT 改成具体的数字之后就跑通了，外部的udp server 也收到了 Android 真机发的内容。

**Comment by halx99** [comment]
@superlixun 定义了还报错?

**Comment by halx99** [comment]
我试了试，没啥问题：
![image](https://user-images.githubusercontent.com/6977319/71310150-9b9b1300-244b-11ea-990d-b8e3782ad0e0.png)

**Comment by superlixun** [comment]
@halx99 我也log了枚举的值，正确的log了值，但跑测试就是崩，我周一再试试，复现的话贴下测试代码。

**Comment by halx99** [comment]
好
