### ISSUE TITLE
功能越来越强大了，考虑加入SSL/TLS功能吗？

### ISSUE THREAD

**Issue by abc100m** [simdsoft/yasio#2]
xxsocket 是当前最好用的socket库，现在看来作者正在加入越来越多的功能了，考虑加入SSL/TLS功能吗？

PS: 难得见到C++功力这么深厚的大神！

**Comment by halx99** [comment]
呵呵，谬赞了，只是一个小工具类，本没打算加什么功能，不过你说的ssl这个可以研究一下

**Comment by abc100m** [comment]
这里有个支持TLS的库， 看起来还不错的样子。 https://github.com/cesanta/krypton

**Comment by halx99** [comment]
好的，多谢推荐， 有空看看能否集成进来

**Comment by sgf** [comment]
如果 加入 SSL的话 倒是建议 分开做 
或者做成插件的形式。现在很多socket 或者 tcp 库  功能都很强大，但是有些功能其实是多余的 反倒臃肿 😂。

**Comment by halx99** [comment]
是的

**Comment by halx99** [comment]
https://github.com/ezhangle/krypton
