### ISSUE TITLE
pconnect_n超时问题

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#201]
int pconnect_n(const char* hostname, u_short port,
                             const std::chrono::microseconds& wtimeout, u_short local_port = 0);
这个运行，我发现超时是两倍wtimeout，设一秒，两秒报超时。
mac上测试的。

**Comment by halx99** [comment]
你是传的域名吗

**Comment by halx99** [comment]
看看域名是不是返回了多个ip地址

**Comment by airx** [comment]
> 看看域名是不是返回了多个ip地址

IP地址
![image](https://user-images.githubusercontent.com/1214492/72165447-7a05c980-3402-11ea-952a-287879df046e.png)

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/72202090-76238700-3496-11ea-98da-131e7fc0b68c.png)

除非这里select执行两次，否则，时间不会是双倍

**Comment by airx** [comment]
xpconnect_n和pconnect_n执行了两次select；connect_n执行了一次select。
xpconnect_n，pconnect_n和connect_n各自含义，好像你说的是ipv4和ipv6，具体用哪个好点呢，或者说无脑用哪个就对了，不用考虑什么情况。

**Comment by halx99** [comment]
![image](https://user-images.githubusercontent.com/6977319/72203385-2ea4f700-34a6-11ea-988c-a6539d59c25b.png)

xpconnect你看看这个list， 会不会有两个

**Comment by halx99** [comment]
pconnect_n是直接调用connect_n不会进行域名解析

**Comment by airx** [comment]
> ![image](https://user-images.githubusercontent.com/6977319/72203385-2ea4f700-34a6-11ea-988c-a6539d59c25b.png)
> 
> xpconnect你看看这个list， 会不会有两个

对，是2个，如果换成域名www.baidu.com，就变成4个了

**Comment by halx99** [comment]
擦，这么神奇，直接写ip地址，尽然还能有两个

**Comment by airx** [comment]
> 擦，这么神奇，直接写ip地址，尽然还能有两个

嗯，你试试呢

**Comment by halx99** [comment]
我手上没有mac电脑，我win10上测试超时正常

**Comment by halx99** [comment]
我用travis ci跑了下，还真是:
![image](https://user-images.githubusercontent.com/6977319/72206651-89047e80-34cb-11ea-8721-c8794334fe41.png)

**Comment by halx99** [comment]
我找到问题所在了

**Comment by halx99** [comment]
修复了: 
![image](https://user-images.githubusercontent.com/6977319/72209510-08a14600-34ea-11ea-9859-7631b4faac30.png)

**Comment by airx** [comment]
> 我找到问题所在了

这个会影响udp吗？

**Comment by halx99** [comment]
不会
