### ISSUE TITLE
Improve xxsocket send_n/recv_n implementation and behavior.

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#202]
recv_n的timeout参数我理解为，超过timeout时间未收到指定的长度，或者完全未收到，返回失败，比如-1。
但是现在完全出不来，一直在里面循环执行。
![image](https://user-images.githubusercontent.com/1214492/72159220-d95ddc80-33f6-11ea-8283-81ada2446fdc.png)

**Comment by halx99** [comment]
The behavior of xxsocket API, all functions contains suffix _n will set socket to nonblocking mode, and not restore the status of it.

**Comment by halx99** [comment]
不能说有bug，可能行为不符合你的预期?

**Comment by airx** [comment]
recv超时收取有什么办法吗

**Comment by airx** [comment]
我的目的是要做个同步收发的函数，类似rpc调用，connect，send，recv这样一个流程的，需要有超时才好办，或者你有更好办法实现吗？

**Comment by halx99** [comment]
我试试这个接口

**Comment by halx99** [comment]
这里其实你是希望总时间到了，就退出来？

**Comment by halx99** [comment]
```cpp 从最新ACE源码找到了
ssize_t
ACE::recv_n_i (ACE_HANDLE handle,
               void *buf,
               size_t len,
               const ACE_Time_Value *timeout,
               size_t *bt)
{
  size_t temp;
  size_t &bytes_transferred = bt == 0 ? temp : *bt;
  ssize_t n;
  ssize_t result = 0;
  int error = 0;

  int val = 0;
  ACE::record_and_set_non_blocking_mode (handle, val);

  for (bytes_transferred = 0;
       bytes_transferred < len;
       bytes_transferred += n)
    {
      // Try to transfer as much of the remaining data as possible.
      // Since the socket is in non-blocking mode, this call will not
      // block.
      n = ACE::recv_i (handle,
                       static_cast <char *> (buf) + bytes_transferred,
                       len - bytes_transferred);

      // Check for errors.
      if (n == 0 ||
          n == -1)
        {
          // Check for possible blocking.
          if (n == -1 &&
              errno == EWOULDBLOCK)
            {
              // Wait upto <timeout> for the blocking to subside.
              int const rtn = ACE::handle_read_ready (handle, timeout);

              // Did select() succeed?
              if (rtn != -1)
                {
                  // Blocking subsided in <timeout> period.  Continue
                  // data transfer.
                  n = 0;
                  continue;
                }
            }

          // Wait in select() timed out or other data transfer or
          // select() failures.
          error = 1;
          result = n;
          break;
        }
    }

  ACE::restore_non_blocking_mode (handle, val);

  if (error)
    return result;
  else
    return static_cast<ssize_t> (bytes_transferred);
}
```

**Comment by halx99** [comment]
https://github.com/DOCGroup/ACE_TAO/blob/master/ACE/ace/ACE.cpp 852行 recv_n

**Comment by halx99** [comment]
嗯，这里行为的确不会退出来，除非链接断开

**Comment by airx** [comment]
> 这里其实你是希望总时间到了，就退出来？

我想实现一个同步收发，原理上应该是这么个流程：
response syncCall(request, timeout) {
connect;
send;
recv;
close;
return response;
}
timeout是这个请求总的超时时间，至少包含connect和recv的超时时间，所以connect和recv都应该有个超时机制才行啊。

**Comment by halx99** [comment]
Since commit: https://github.com/simdsoft/yasio/commit/6d77ff8e14e8cd0850e8060a39f41d9199adb3bc (may release with v3.31.2), The behavior of xxsocket API, all functions contains suffix ```_n``` will set socket to nonblocking mode, and not restore the status of it.

**Comment by airx** [comment]
v3.31.2什么时候release？

**Comment by halx99** [comment]
你确认一下pconnect_n问题

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: airx <notifications@github.com>
发送时间: Saturday, January 11, 2020 6:20:58 PM
收件人: simdsoft/yasio <yasio@noreply.github.com>
抄送: HALX99 <halx99@live.com>; State change <state_change@noreply.github.com>
主题: Re: [simdsoft/yasio] Improve xxsocket send_n/recv_n implementation and behavior. (#202)


v3.31.2什么时候release？

―

**Comment by airx** [comment]
recv_n的第二个参数len：
指的是要在timeout时间内，必须收到len长度的buffe，否则都不对；还是一个大的缓冲区的长度，只要收到了就对。
我测试好像是第二种情况，跟你确认下。

**Comment by halx99** [comment]
收多少，是多少

**Comment by halx99** [comment]
你可以自己判断，收到长度不等于请求长度，视为失败

**Comment by halx99** [comment]
3.31.2 release了

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Lake Deal <halx99@live.com>
Sent: Saturday, January 11, 2020 6:24:51 PM
To: simdsoft/yasio <reply@reply.github.com>
Subject: 回复: [simdsoft/yasio] Improve xxsocket send_n/recv_n implementation and behavior. (#202)


你确认一下pconnect_n问题



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用



________________________________
发件人: airx <notifications@github.com>
发送时间: Saturday, January 11, 2020 6:20:58 PM
收件人: simdsoft/yasio <yasio@noreply.github.com>
抄送: HALX99 <halx99@live.com>; State change <state_change@noreply.github.com>
主题: Re: [simdsoft/yasio] Improve xxsocket send_n/recv_n implementation and behavior. (#202)


v3.31.2什么时候release？

―
