### ISSUE TITLE
建议service还是增加个write buffer方法

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#205]
现在是vector: int write(transport_handle_t transport, std::vector<char> buffer)；
建议增加void *buffer（或者char *buffer）参数都可以的write方法，方便一点；obstream不一定会用到。
我自己包装了一个，但更新版本每次还涉及比较，就比较麻烦了。

**Comment by halx99** [comment]
嗯嗯，可以考虑增加重装版本

**Comment by halx99** [comment]
@airx
你可以提交个PR, 加个重载版本，我来merge
int write(transport_handle_t transport, const void* buf, int len)；

**Comment by airx** [comment]
> @airx
> 你可以提交个PR, 加个重载版本，我来merge
> int write(transport_handle_t transport, const void* buf, int len)；

int write(transport_handle_t transport, const void *buf, int len) {
  	  std::vector<char> buffer((char*)buf, (char*)buf+len);
	  return write(transport, std::move(buffer));
 }
应该是这样，PR我不太会搞，代码语法方面我写的不好看，还是你斟酌吧^^

**Comment by halx99** [comment]
@airx 加好了，试试吧
