### ISSUE TITLE
schedule方法之前有个repeate参数，现在没有了吗？

### ISSUE THREAD

**Issue by airx** [simdsoft/yasio#206]
如题，要重复执行怎么办？嵌套？

**Comment by halx99** [comment]
对，交给业务重复注册，参见: https://github.com/simdsoft/ftp_server/blob/master/ftp_session.cpp

**Comment by airx** [comment]
问几个问题哈：
1、deadline_timer的cancel()调用后，作用是什么？是影响待执行的timer_cb_t的入参bool cancelled为true吗？
2、deadline_timer的unschedule方法是不是service的schedule方法的逆行操作？
3、假设service调用了stop_service()方法，是不是该service相关的deadline_timer都自动不执行了？
4、deadline_timer的timer_cb_t是不是在service的线程里面跑的？

**Comment by halx99** [comment]
1. 没错
2. 没错，和cancel不同的是，不会执行timer的回调
3. 没错，所有timer回调都不会执行
4. 没错，直接在线程跑，之所以这样设计，是可以满足那种游戏切后台可能也需要和服务器保持心跳的情况

**Comment by airx** [comment]
>     1. 没错
> 
>     2. 没错，和cancel不同的是，不会执行timer的回调
> 
>     3. 没错，所有timer回调都不会执行
> 
>     4. 没错，直接在线程跑，之所以这样设计，是可以满足那种游戏切后台可能也需要和服务器保持心跳的情况

谢谢，晓得线程模型了，编码才好注意相关问题。

**Comment by halx99** [comment]
You are welcome
