### ISSUE TITLE
The kcp/ssl/jsb/luabinding need adapte new udp transport implemention

### ISSUE THREAD

**Issue by halx99** [simdsoft/yasio#224]

**Comment by airx** [comment]
udp的版本release了吗

**Comment by halx99** [comment]
快了，等这个issue关闭

**Comment by halx99** [comment]
@airx merge了，pull最新master试试udp吧， 新版本udp-client默认不绑定的， 新增io_service::write_to接口

**Comment by airx** [comment]
> @airx merge了，pull最新master试试udp吧， 新版本udp-client默认不绑定的， 新增io_service::write_to接口

好的，我试试；另外提个问题，scheduler能搞个可重复的吗？

**Comment by halx99** [comment]
@airx 看这个，最新master已支持，timer_cb_t回调函数返回值改为bool，返回true只执行一次，返回false继续schedule
