### ISSUE TITLE
std::thread will crash on some cross compiler @arix

### ISSUE THREAD

**Issue by halx99** [simdsoft/yasio#244]

**Comment by airx** [comment]
https://blog.csdn.net/caishi8860/article/details/83781009
海思官方给出的编译参数：
CFLAGS += -mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -mno-unaligned-access -fno-aggressive-loop-optimizations
    CXXFlAGS +=-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -mno-unaligned-access -fno-aggressive-loop-optimizations
就解决了

**Comment by halx99** [comment]
好, 完美
