### ISSUE TITLE
unity c# 以及 xlua问题

### ISSUE THREAD

**Issue by Ander456** [simdsoft/yasio#253]
问题描述：
1. 是否可以不用lua直接在unity 用c#使用哈 有没有文档 - - 
2. 如果用xlua 我看了下文档的链接工程的CMakeFile.txt 发现并没有引入sol那还能正常使用么

**Comment by halx99** [comment]
1. 可以，后续会补充文档
2. 看xlua编译使用的c++标准，如果支持c++17或以上标准，则使用的sol, 否则使用的[kaguya](https://github.com/satoren/kaguya)

**Comment by halx99** [comment]
另外sol2是仅头文件的库，无需加入cmake编译

**Comment by Ander456** [comment]
感谢回答。如果能给出 更详细的文档就更好了

**Comment by halx99** [comment]
注意，kaguya，请不要试图使用官方，官方在*nix平台下有bug, 请使用yasio内置

**Comment by Ander456** [comment]
重新做了一下 xlua的集成
1. xlua 最新工程
2. 按照示例项目的CMakefile.txt yasio部分填写 （删掉c-ares部分）
3. c#部分 增加 dllimport 部分 

结果：完成
