### ISSUE TITLE
unity xlua error

### ISSUE THREAD

**Issue by Ander456** [simdsoft/yasio#265]
1. 
```
#begin yasio
set (YASIO_SRC
    yasio/yasio/ibstream.cpp
    yasio/yasio/obstream.cpp
    yasio/yasio/xxsocket.cpp
    yasio/yasio/yasio.cpp
    yasio/yasio/bindings/lyasio.cpp
    yasio/yasio/bindings/yasio_ni.cpp
)
set_property(
    SOURCE ${YASIO_SRC}
    APPEND
    PROPERTY COMPILE_DEFINITIONS
    LUA_LIB
)
list(APPEND THIRDPART_INC yasio)
set (THIRDPART_SRC ${THIRDPART_SRC} ${YASIO_SRC})
#end yasio
```

2. 
```
 [DllImport(LUADLL, CallingConvention = CallingConvention.Cdecl)]
		public static extern int luaopen_yasio(System.IntPtr L);

[MonoPInvokeCallback(typeof(LuaDLL.lua_CSFunction))]
        public static int LoadYasio(System.IntPtr L)
        {
			return luaopen_yasio(L);
        }
```

3. 
![image](https://user-images.githubusercontent.com/20219696/80083799-94fee280-8588-11ea-84a2-7172536400e1.png)

4. 
![image](https://user-images.githubusercontent.com/20219696/80083828-a0eaa480-8588-11ea-9e1f-2a0d294c9d1d.png)

**Comment by Ander456** [comment]
when call service.start(function(xxx)
error is :
LuaException: maybe...Argument mismatch:function	 candidate is:
		PN5yasio4inet10io_serviceE,N6kaguya11LuaFunctionE,

**Comment by halx99** [comment]
ok, let me see

**Comment by halx99** [comment]
I can't repreduce, please use https://github.com/yasio/empty3d to test directly

**Comment by halx99** [comment]
注意，kaguya，请不要试图使用官方，官方在*nix平台下有bug, 请使用yasio内置

**Comment by halx99** [comment]
because we can't repreduce this issue, I will colse this issue, if you have any question later, you still can reopen it.
