### ISSUE TITLE
如何从 io_event 中获取 user data

### ISSUE THREAD

**Issue by miloyip** [simdsoft/yasio#271]
当建立连接后，应用程序需要把连接关联到一些数据（例如用户信息等）。
在我的测试程序中，现时是通过 io_event 的 transport handle 去做查询，如：

~~~cpp
std::unordered_map<transport_handle_t, std::shared_ptr<Client>> clients;

service.start([&](event_ptr&& event) {
    switch (event->kind()) {
    case YEK_CONNECT_RESPONSE:
        clients.insert({ event->transport(), std::shared_ptr<Client>(new Client { /* ... */ });
        break;
    case YEK_CONNECTION_LOST:
        {
            auto itr = clients.find(event->transport()); // TODO: eliminate lookup
            // ...
            clients.erase(itr);
        }
    case YEK_PACKET:
        {
            auto itr = clients.find(event->transport()); // TODO: eliminate lookup
            // ...
        }
});
~~~

但这样要做查找，不知道有没有更好的使用方法？还是我对 API 设计有所误解？

**Comment by halx99** [comment]
transport有个公开的成员ud_, 类型如下:
union
  {
    void* ptr;
    int ival;
  } ud_;
你可以保存用户数据，但注意生命周期需要你自己维护，收到connect success存储你的userdata, 收到connect lost事件，清理你的userdata

**Comment by halx99** [comment]
另外注意一下: YEK_CONNECT_RESPONSE需要检查status状态， 如果不为0， transport句柄是nullptr

**Comment by halx99** [comment]
具体还可以参考ftp_server example里对ftp_session的管理:
https://github.com/yasio/ftp_server/blob/master/ftp_server.cpp

**Comment by miloyip** [comment]
谢谢。之前只看了 https://docs.yasio.org/zh_CN/latest/api/classes/io_transport.html 没仔细看代码。

**Comment by halx99** [comment]
> 谢谢。之前只看了 https://docs.yasio.org/zh_CN/latest/api/classes/io_transport.html 没仔细看代码。

不客气，我后续补一下文档

**Comment by IronsDu** [comment]
@halx99 我觉得，如果网络event是基于TcpSession，就没有这个问题。
TcpSession的回调函数可以capture 业务层的对象。就不需要再反查了。

**Comment by halx99** [comment]
> @halx99 我觉得，如果网络event是基于TcpSession，就没有这个问题。
> TcpSession的回调函数可以capture 业务层的对象。就不需要再反查了。

嗯，是的， transport_handle本身就可以视为TcpSession

**Comment by halx99** [comment]
更新: 最新ftp_server提交已免去```std::unordered_map```查询，直接用```userdata```管理```ftp_session```生命周期: https://github.com/yasio/ftp_server/blob/master/ftp_server.cpp#L98
