### ISSUE TITLE
Does the lib handles connections behind NATs?

### ISSUE THREAD

**Issue by FabioNevesRezende** [simdsoft/yasio#28]
Hello, does the library supports connections to be stablished between NATs or the user must manually open port forwarding/use upnp or something like this?

**Comment by halx99** [comment]
Do you mean P2P connections?
Currently, this lib does not support p2p connections.

**Comment by Moobywotsit** [comment]
Any Progress on this at all?? the integration with Cocos2d-x is of particular interest with this library, if you add the p2p I think it will be about the only lib which integrates nicely with p2p!

**Comment by halx99** [comment]
- [ ] hello ok?

**Comment by halx99** [comment]
Because the P2P implementation code isn't genral, so I mark this issue to 'wontfix', if anyone have better idea, welcome to send PR
