### ISSUE TITLE
增加js的udp,kcp使用例子

### ISSUE THREAD

**Issue by fanhaining** [simdsoft/yasio#286]
cpp看不太懂，搞半天没搞成功，麻烦添加一下

**Comment by halx99** [comment]
@243011068 你cocos creator版本多少？

**Comment by fanhaining** [comment]
2.4，我现在编译成功了，如何使用kcp有点懵

**Comment by fanhaining** [comment]
有没有群什么的可以加

**Comment by halx99** [comment]
> 有没有群什么的可以加

刚创建了个QQ群： 829884294

**Comment by halx99** [comment]
https://github.com/yasio/inettester
