### ISSUE TITLE
yasio http client 支持

### ISSUE THREAD

**Issue by justbilt** [simdsoft/yasio#307]
目前感觉项目 Cocos 内置的两个网络库 http / websocket 都有些问题, 打算换掉, 找了一圈还是 yasio 最符合我的需求.

但是我看到文档中并没有写到 http 的支持, 搜索后看到有一个 http_client.lua 的示例, 但是没有 js 版本的. 请问 yasio 目前对 http 的支持如何?

**Comment by halx99** [comment]
理论上， 你利用yasio加上一个http_parser可以实现http的完整功能，http_client.lua只是一个演示，请求和接受都是原始http数据包
yasio甚至也支持基于openssl的TLS（cocos中基本都集成了openssl）, 因此https传输也是可以实现的

**Comment by halx99** [comment]
yasio的核心是非阻塞多路io复用socket库，因此核心是没有http的，即使将来计划支持，应该也是以扩展的形式

**Comment by justbilt** [comment]
明白, 谢谢您的回复. 我先尝试把 socket 库换了, 期待 yasio 加上 http 支持, 变成一套网络解决方案.

**Comment by halx99** [comment]
- 基于yasio的HttpClient最佳实践(Merged): https://github.com/adxeproject/adxe/pull/390
- 独立扩展实现：https://github.com/yasio/yasio/tree/dev/extensions/yasio_http
- 独立扩展测试程序： https://github.com/yasio/yasio/blob/dev/tests/http/main.cpp
