### ISSUE TITLE
关于TCP粘包处理

### ISSUE THREAD

**Issue by createwindow** [simdsoft/yasio#313]
请问TCP粘包处理是怎么做的？需要业务添加数据长度吗？

**Comment by halx99** [comment]
设置信道的拆包参数即可，详见: https://docs.yasio.org/zh_CN/latest/api/classes/io_service.html#io-service-set-option

**Comment by createwindow** [comment]
> 设置信道的拆包参数即可，详见: https://docs.yasio.org/zh_CN/latest/api/classes/io_service.html#io-service-set-option

感谢
