### ISSUE TITLE
Is kcp working?

### ISSUE THREAD

**Issue by amunhoz** [simdsoft/yasio#316]
It looks like the tests with kcp are not working properly.

echo_client -> does not connect to echo server
speed -> cant compile, error: 
```
tests/speed/main.cpp: In function ‘void setup_kcp_transfer(yasio::inet::transport_handle_t)’:
tests/speed/main.cpp:130:58: error: invalid static_cast from type ‘yasio::inet::transport_handle_t {aka yasio::inet::io_transport*}’ to type ‘yasio::inet::io_transport_kcp*’
   auto kcp_handle = static_cast<io_transport_kcp*>(handle)->internal_object();
```

Used code from git clone and latest version.

Thanks

**Comment by halx99** [comment]
please pass -DYASIO_BUILD_WITH_KCP=1 to cmake

**Comment by amunhoz** [comment]
It worked, but the speed of kcp in local machine it's almost 5 times slower than tcp, is that correct?  Or kcp will only be faster in "bad connection" scenarios?

**Comment by halx99** [comment]
You can refer to kcp readme for more information:
https://github.com/skywind3000/kcp/blob/master/README.en.md

And I think, kcp needs more buffer copy and protocol process on user mode, that maybe why kb/s less than tcp (implement at kernel)
