### ISSUE TITLE
EVENT_TCP_CONNECT_CLOSE not received when wifi off on iOS

### ISSUE THREAD

**Issue by lionloveqin** [simdsoft/yasio#322]
在iOS上，关闭WIFI后，yasio没有发送EVENT_TCP_CONNECT_CLOSE 事件，在Android上会发送的，请问这是什么原因呢？

**Comment by halx99** [comment]
可能是系统策略差异造成，你试着按照下面的链接设置下tcp底层协议的keepalive: 
https://github.com/yasio/yasio/blob/master/tests/tcp/main.cpp#L244
然后再测试，按照代码里注释说明等待时间后，看看是否会触发close事件

**Comment by halx99** [comment]
可能是系统策略差异造成，你试着按照我的链接设置下tcp底层协议的keepalive, 然后再测试，按照代码里注释说明等待时间后，看看是否会触发close事件
