### ISSUE TITLE
Compile error in yasio_cclua.cpp

### ISSUE THREAD

**Issue by Xrysnow** [simdsoft/yasio#340]
I got strange compile error in `yasio_cclua.cpp`  in VS2019, it gave errors in cocos headers. I found it caused by the order of include since the problem solved after I move `#include "cocos2d.h"` to the top. I think it's better to fix this.
https://github.com/yasio/yasio/blob/730a350db5414a392076b33370327f56f10f9164/yasio/bindings/yasio_cclua.cpp#L29-L36

**Comment by halx99** [comment]
Please provide the error log

**Comment by Xrysnow** [comment]
> 已启动生成…
1>------ 已启动生成: 项目: ext_yasio, 配置: Release Win32 ------
1>yasio_cclua.cpp
1>D:\MyEngine\frameworks\cocos2d-x\cocos\base/CCConsole.h(63,43): error C3646: “CC_FORMAT_PRINTF”: 未知重写说明符
1>D:\MyEngine\frameworks\cocos2d-x\cocos\base/CCConsole.h(63,59): error C2059: 语法错误:“(”
1>D:\MyEngine\frameworks\cocos2d-x\cocos\base/ccUTF8.h(66,52): error C3646: “CC_FORMAT_PRINTF”: 未知重写说明符
1>D:\MyEngine\frameworks\cocos2d-x\cocos\base/ccUTF8.h(66,68): error C2059: 语法错误:“(”
1>已完成生成项目“ext_yasio.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by halx99** [comment]
Changed

**Comment by halx99** [comment]
https://github.com/yasio/yasio/commit/68cd461914fe8baac9738e4203992333a521a6af

**Comment by halx99** [comment]
The latest commit may explain the root cause.
