### ISSUE TITLE
Missing lua_isinteger when using c++11 with Lua<=5.2

### ISSUE THREAD

**Issue by Xrysnow** [simdsoft/yasio#341]
`lua_isinteger`  is used in `lyasio.cpp` but not defiened when using c++11 with Lua<=5.2. For c++>=14, it uses `sol` which has a compatible `lua_isinteger` for Lua<=5.2. But for c++11 it uses `kaguya` which do not provide one. The problem fixed after I copied it from `sol.hpp`.

I forgot to copy the compile log but in brief it said `undeclared identifier 'lua_isinteger' in lyasio.cpp`.

**Comment by halx99** [comment]
Thanks for your report, this issue should be fixed by the commit: https://github.com/yasio/yasio/commit/2b064c7c396236e99eacbef6a77674195afd55be
