### ISSUE TITLE
Compile error "yasio-3.37.5/examples/ftp_server does not contain a CMakeLists.txt file"

### ISSUE THREAD

**Issue by zhaowq32** [simdsoft/yasio#353]
examples/ftp_server/CMakeList.txt is not included in the release package.

**Comment by zhaowq32** [comment]
I know I didn’t get the submodule.It is recommended to include all code files in the distribution package.

**Comment by halx99** [comment]
Thanks, next release will include all code files

**Comment by halx99** [comment]
Now, the 3.37.5 full package can be downlad https://github.com/yasio/yasio/releases/download/v3.37.5/yasio-3.37.5.7z
