### ISSUE TITLE
关于io_service中stop函数的问题

### ISSUE THREAD

**Issue by koobin** [simdsoft/yasio#360]
###     鉴于以上问题能否考虑在stop函数中先close掉所有channel，然后再关闭所有timer，等待所有transport关闭再释放所有transport相关资源？

**Comment by halx99** [comment]
ON_OPEN关联的是transport，需要释放的估计也就是trensport的userdata

**Comment by koobin** [comment]
> ON_OPEN关联的是transport，需要释放的估计也就是trensport的userdata

基本是这样的，可以使得程序操作逻辑更加清楚。是否可以考虑建议？

**Comment by halx99** [comment]
那估计的考虑线程问题，另外timer可以调度传cancel= true

**Comment by halx99** [comment]
你有现成的修改方法吗？

**Comment by koobin** [comment]
> 你有现成的修改方法吗？

需要修改的地方稍多，目前正在修改，还没有完成现成的修改方法。

**Comment by halx99** [comment]
另外， timer cancelled后是否需要调度，早期版本会调度，后来某个版本去除了，cancelled后就不再调度timer回调，这一点和asio不一样

**Comment by koobin** [comment]
> 你有现成的修改方法吗？

已提交了PR。
