### ISSUE TITLE
可以强制设置成小端模式发送么？  我根据文档设置成fast_obstream 在serive:write的时候提示类型不匹配

### ISSUE THREAD

**Issue by uurain** [simdsoft/yasio#370]
环境是把最新的工程build到xlua中

**Comment by halx99** [comment]
write接受参数是字节buffer: yasio::sbyte_buffer, fast_obstream通过API buffer()拿到sbyte_buffer

**Comment by uurain** [comment]
在lua中不管是yasio.obstream还是 yasio.fast_obstream new出来的都没有buff()方法,只有to_string()方法 测试可以发送出去 ，但是截包发现yasio.fast_obstream 还是大端模式，有什么别的接口可以强制小端么？

**Comment by halx99** [comment]
> 在lua中不管是yasio.obstream还是 yasio.fast_obstream new出来的都没有buff()方法,只有to_string()方法 测试可以发送出去 ，但是截包发现yasio.fast_obstream 还是大端模式，有什么别的接口可以强制小端么？

to_string按理说可以

**Comment by halx99** [comment]
你的编译环境是啥，c++14以上吗？

**Comment by halx99** [comment]
fast 和非fast写入几个数值数据，to_string对比是一样的?

**Comment by uurain** [comment]
我错了 fast_obstream:to_string() 是ok的，昨天截图看错了位置，服务器有回包，然后自带的粘包处理应该也是大小端问题 导致没有走YEK_PACKET回调， 粘包的能设置大小端么。。

**Comment by halx99** [comment]
对，内置拆包是大端

**Comment by halx99** [comment]
我看下加个配置

**Comment by uurain** [comment]
![image](https://user-images.githubusercontent.com/3994429/149264639-3fe73af7-2d92-4ab5-9c93-6fb5e0b87f7b.png)
我这里收到的前两个字节是22,00也就是34 总长度是36 我的包头不包含长度 所以设置的参数是self.client:set_option(yasio.YOPT_C_LFBFD_PARAMS,
            0, -- channelIndex, 信道索引    
            65535, -- maxFrameLength, 最大包长度
            0,  -- lenghtFieldOffset, 长度字段偏移，相对于包起始字节
            2, -- lengthFieldLength, 长度字段大小，支持1字节，2字节，3字节，4字节
            2 -- lengthAdjustment：如果长度字段字节大小包含包头，则为0， 否则，这里=包头大小
    )
为啥木有回调呀？

**Comment by halx99** [comment]
就是大小端问题，你的截图数据是小端

**Comment by uurain** [comment]
好的 求大佬加个配置接口

**Comment by halx99** [comment]
一会儿加

**Comment by halx99** [comment]
已添加选项

**Comment by uurain** [comment]
加了参数 收到YEK_PACKET ok了 但是local ibs = event:packet()返回的Ibs默认应该也是大端，，，这个有啥办法么？看到有个fast_ibstream 但是不清楚怎么转换

**Comment by halx99** [comment]
lua绑定哪里估计需要再加个参数才行

**Comment by halx99** [comment]
或者统一成flag: default(0), no_swap(1), (2)raw

**Comment by halx99** [comment]
YPT_DEFAULT, YPT_NSW, YPT_RAW

**Comment by uurain** [comment]
你回复的3个flag我在源码里面搜没搜索到  - -

**Comment by halx99** [comment]
还没加，不过sol2，lua绑定貌似不行，返回值类型不同，无法编译，所以估计得加接口才行，比如： event:fast_packet()

**Comment by uurain** [comment]
好  坐等大佬加接口！！

**Comment by halx99** [comment]
sol2的绑定加好了，可以用标记为，无需新增接口: https://github.com/yasio/yasio/commit/ab5ef3c866437b324291a531c0ce4405aca77371

**Comment by halx99** [comment]
> 好 坐等大佬加接口！！

 又提交了下，更新下，应该ok了

**Comment by uurain** [comment]
目前在mac上测试通过啦 后续会打包在手机上试试。感谢大佬！

**Comment by halx99** [comment]
ok
