### ISSUE TITLE
KCP packet limitation

### ISSUE THREAD

**Issue by amunhoz** [simdsoft/yasio#373]
Hi there again, i was testing you lib in the past, now i'm trying again.
There is one thing i think should be working differently.

With KCP connection, the package size IS LIMITED to the MTU setted with:
::ikcp_setmtu(kcp_handle, opt_mtu);

So, if i set the MTU to 1400 and try to send a 2kb packet, it doesn't work.
As i know, the MTU  should be defined based on the network configuration, not exactly on desired packet size.
It seems like the TCP connection works differently, not limited by the MTU.

Here is the log with mtu 1400 and an attemp to send 10kb
`
[yasio][1644002767686][global] the yasio-3.37.2 is initialized, the size of per transport is 65952 when object_pool enabled.

[yasio][1644002767686][global] sizeof(io_event)=64

[yasio]xxsocket::traverse_local_address: ip=127.0.0.1
[yasio]xxsocket::traverse_local_address: ip=10.0.0.227
[yasio]xxsocket::traverse_local_address: ip=172.17.0.1
[yasio]xxsocket::traverse_local_address: ip=10.99.10.2
[yasio]xxsocket::traverse_local_address: ip=::1
[yasio]xxsocket::traverse_local_address: ip=fe80::8da6:95f4:43a5:dc66
[yasio]xxsocket::traverse_local_address: ip=fe80::42:a4ff:fe79:73c0
[yasio]xxsocket::traverse_local_address: ip=fe80::f095:fff:fef4:3f74
[yasio]xxsocket::traverse_local_address: ip=fe80::e81b:f5ff:fe1e:af3f
[yasio]xxsocket::traverse_local_address: ip=fe80::d4a9:deff:fef5:cc9f
[yasio]xxsocket::traverse_local_address: ip=fe80::b027:8ff:fe79:97a1
[yasio]xxsocket::traverse_local_address: ip=fe80::f41a:9eff:fe9c:f59d
[yasio]xxsocket::traverse_local_address: ip=fe80::244b:4fff:fe1c:8daf
[yasio]xxsocket::getipsv: flags=1
[yasio][1644002767688][core] socket.select max_nfds_:18 waiting... 300000 milliseconds

[yasio][1644002767688][core] socket.select waked up, retval=1

[yasio]xxsocket::traverse_local_address: ip=127.0.0.1
[yasio]xxsocket::traverse_local_address: ip=10.0.0.227
[yasio]xxsocket::traverse_local_address: ip=172.17.0.1
[yasio]xxsocket::traverse_local_address: ip=10.99.10.2
[yasio]xxsocket::traverse_local_address: ip=::1
[yasio]xxsocket::traverse_local_address: ip=fe80::8da6:95f4:43a5:dc66
[yasio]xxsocket::traverse_local_address: ip=fe80::42:a4ff:fe79:73c0
[yasio]xxsocket::traverse_local_address: ip=fe80::f095:fff:fef4:3f74
[yasio]xxsocket::traverse_local_address: ip=fe80::e81b:f5ff:fe1e:af3f
[yasio][1644002767688][index: 0] open server succeed, socket.fd=18 listening at 127.0.0.1:5557...

[yasio][1644002767688][core] socket.select max_nfds_:19 waiting... 300000 milliseconds

[yasio]xxsocket::traverse_local_address: ip=fe80::d4a9:deff:fef5:cc9f
[yasio]xxsocket::traverse_local_address: ip=fe80::b027:8ff:fe79:97a1
[yasio]xxsocket::traverse_local_address: ip=fe80::f41a:9eff:fe9c:f59d
[yasio]xxsocket::traverse_local_address: ip=fe80::244b:4fff:fe1c:8daf
[yasio]xxsocket::getipsv: flags=1
[yasio][1644002767688][core] socket.select max_nfds_:20 waiting... 300000 milliseconds

[yasio][1644002767688][core] socket.select waked up, retval=1

[yasio][1644002767690][index: 0] connecting server 127.0.0.1(127.0.0.1):5557...

[yasio][1644002767690][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002767690][index: 0] the connection #3(0x7fd130004ef0) [127.0.0.1:45505] --> [127.0.0.1:5557] is established.

[yasio][1644002767690][core] socket.select max_nfds_:21 waiting... 300000 milliseconds

[yasio][1644002768691][core] socket.select waked up, retval=1

[yasio][1644002768691][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768691][core] socket.select max_nfds_:21 waiting... 20 milliseconds

[yasio][1644002768691][core] socket.select waked up, retval=1

[yasio][1644002768693][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768693][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768693][index: 0] the connection #4(0x7fd13c014f00) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768693][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768693][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768693][core] socket.select waked up, retval=1

[yasio][1644002768694][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768694][index: 0] the connection #5(0x7fd13c0350c0) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768694][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768694][core] socket.select max_nfds_:21 waiting... 17 milliseconds

[yasio][1644002768694][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768694][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768694][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768694][core] socket.select waked up, retval=1

[yasio][1644002768695][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768695][core] socket.select max_nfds_:21 waiting... 16 milliseconds

[yasio][1644002768695][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768695][index: 0] the connection #6(0x7fd13c056340) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768695][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768695][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768695][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768695][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768695][core] socket.select waked up, retval=1

[yasio][1644002768695][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][core] socket.select max_nfds_:21 waiting... 15 milliseconds

[yasio][1644002768696][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768696][index: 0] the connection #7(0x7fd13c0775c0) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768696][core] socket.select waked up, retval=1

[yasio][1644002768696][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768696][index: 0] the connection #8(0x7fd13c099900) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768696][core] socket.select max_nfds_:21 waiting... 15 milliseconds

[yasio][1644002768696][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][core] socket.select waked up, retval=1

[yasio][1644002768697][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768697][core] socket.select max_nfds_:21 waiting... 14 milliseconds

[yasio][1644002768697][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768697][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768698][index: 0] the connection #9(0x7fd13c0bab80) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768698][core] socket.select waked up, retval=1

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][core] socket.select max_nfds_:21 waiting... 13 milliseconds

[yasio][1644002768698][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768698][index: 0] the connection #10(0x7fd13c0dcec0) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768698][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768699][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768699][index: 0] recvfrom peer: 127.0.0.1:45505 succeed.

[yasio][1644002768699][core] socket.select waked up, retval=1

[yasio][1644002768699][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768699][core] socket.select max_nfds_:21 waiting... 12 milliseconds

[yasio][1644002768699][index: 0] sndbuf=212992, rcvbuf=212992

[yasio][1644002768699][index: 0] the connection #11(0x7fd13c0ff200) [127.0.0.1:5557] --> [127.0.0.1:45505] is established.

[yasio][1644002768699][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768699][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768699][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][core] socket.select max_nfds_:30 waiting... 14 milliseconds

[yasio][1644002768700][core] socket.select waked up, retval=1

[yasio][1644002768700][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768700][core] socket.select max_nfds_:21 waiting... 11 milliseconds

[yasio][1644002768712][core] socket.select waked up, retval=0

[yasio][1644002768712][core] do_select is timeout, process_timers()

[yasio][1644002768712][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768712][core] socket.select max_nfds_:21 waiting... 19 milliseconds

[yasio][1644002768714][core] socket.select waked up, retval=0

[yasio][1644002768714][core] do_select is timeout, process_timers()

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

[yasio][1644002768714][index: 0] do_read status ok, bytes transferred: 0, buffer used: 0

`

and goes on...

**Comment by amunhoz** [comment]
There is one way to know the last kcp packet size with "ikcp_peeksize", but i dont see that function been used wity Yasio.
Testing with Ubuntu 20

**Comment by amunhoz** [comment]
Ok, i realized that can be one way to use it.
But, perhaps you can check a better error handle in this situation.

**Comment by halx99** [comment]
The `ikcp_peeksize` invoked by `ikcp_recv`, and yasio always try to call it: https://github.com/yasio/yasio/blob/dev/yasio/yasio.cpp#L681

**Comment by amunhoz** [comment]
Ok, sorry, didnt saw that.  
But did you checked the packet limitation by the KCP mtu?  Usually, KCP handles the correct MTU (usually 1300-1500) in output function, and the packet limit would be much higher than that.
And, on sending a bigger package i got a freeze without an error handling.

**Comment by halx99** [comment]
Yes, I have checked, the behavior is strange, even through I set the `ikcp_update` interval to 0, the recv speed still very slow than send.

**Comment by amunhoz** [comment]
I've got another strange behaviour.
If i try to break the packages to kcp limitation, and try to send sequential packets (without any delay) it gives me the same strange error (lost connection and try to reconnect).
