### ISSUE TITLE
客户端完整使用实例

### ISSUE THREAD

**Issue by xschool2010** [simdsoft/yasio#4]
rt 弱弱地问一句 这个可以有吗-。-

**Comment by halx99** [comment]
正在实现支持P2P的tcp_client, 可以参考

**Comment by xschool2010** [comment]
recv 没接收完跳不出来   应该怎么用啊

**Comment by halx99** [comment]
阻塞模式，默认是要接受完所有数据才跳出来，所以要自己定义数据长度协议，例如
data_len: 2 bytes, data:

**Comment by xschool2010** [comment]
传入长度设多少好啊  如下图我原来size传的8176把把都能出来的 现在阻塞接受  由于每次接收的消息包大小不同 我都不知道设成多大好了   设成1的话会不会影响效率
![qq 20160608134620](https://cloud.githubusercontent.com/assets/15986170/15883962/843242e0-2d7f-11e6-815a-bef51d329423.png)

**Comment by halx99** [comment]
应该是这样子:
假设从自定义协议包头开始接受:

int bodyLen = 0;
int n = recv(m_socketClient, &bodLen, 4, 0);
if(n == 4) 
{
     bodyLen = ntohl(bodyLen);
     char\* buffer = new char[bodyLen];
     n = recv(m_socketClient, buffer, bodyLen, 0);
}

**Comment by xschool2010** [comment]
好的 谢谢  但是不理解为什么你写的是每次接收4字节大小？ 如果我用以下这种每次接收1个字节的方式 不知道会不会有什么不妥之处？
//.h
xxsocket m_xxTcpClient;
unsigned short                          m_wRecvSize;                        //接收长度
unsigned char                           m_cbRecvBuf[SOCKET_PACKAGE];      //接收缓冲
//.cpp
while(m_xxTcpClient.is_open())
{
if (!m_xxTcpClient.alive())
{
    CloseSocket(true);
    break;
}
while(true)
{
    if (!m_xxTcpClient.recv(m_cbRecvBuf, 1)) 
    break;
    if(++m_wRecvSize < wPacketSize)    //数据包大小
    break;
    //...
    处理消息
    //...
}
}

**Comment by halx99** [comment]
4字节表示应用层协议包的长度域，我这里只是举例子，可以是1字节，2字节，4字节，或者8字节整数

**Comment by halx99** [comment]
你可以看一下，我最新上传的应用层二进制协议自动代码生成器，在tools目录下。可根据xm定义，自动生成消息编解码，并支持生成相应的lua 绑定代码

**Comment by xschool2010** [comment]
好的 谢谢 赞一个！
