### ISSUE TITLE
Update to latest mbedtls version

### ISSUE THREAD

**Issue by paulocoutinhox** [simdsoft/yasio#423]
Hi,

We fixed the bug for iOS:
https://github.com/Mbed-TLS/mbedtls/issues/7787

Only need remove the error when warn:
https://github.com/search?q=repo%3AMbed-TLS%2Fmbedtls%20werror&type=code
&
https://github.com/Mbed-TLS/mbedtls/issues/7880

There is an option "MBEDTLS_FATAL_WARNINGS", can you set OFF for MBEDTLS to it work with iOS, tvOS and watchOS?

Thanks.

**Comment by halx99** [comment]
The latest release v4.1.0 already set MBEDTLS_FATAL_WARNINGS for watchos

**Comment by paulocoutinhox** [comment]
Thanks.

Now, everything is working:
https://github.com/paulocoutinhox/cpp-http-test

Android, macOS, iOS, watchOS, tvOS, macCatalyst.
