### ISSUE TITLE
UDP example

### ISSUE THREAD

**Issue by Zhaojiawei2920055606** [simdsoft/yasio#45]
大神，框架很棒，cpptest.cpp中的TCP的例子能大概看懂，但是UDP该如何使用呢求指点，是直接使用xxsocket::open(AF_INET, SOCK_DGRAM) 么?

**Comment by halx99** [comment]
是的，udp目前没有完整的asio封装

**Comment by Zhaojiawei2920055606** [comment]
好的，谢谢

**Comment by halx99** [comment]
@Zhaojiawei2920055606 最新版本增加了udp异步socket通讯，你可以试试
