### ISSUE TITLE
阻塞接收

### ISSUE THREAD

**Issue by xschool2010** [simdsoft/yasio#5]
请问如果我想不阻塞接收数据   每次给一个固定大小的buffer去接收    然后不管是否接收到拘束马上返回 应该怎么修改recv部分呢

**Comment by xschool2010** [comment]
还有就是我close socket时   现在的阻塞接收会结束吗

**Comment by halx99** [comment]
1.不阻塞接受，先调用xxsocket::set_nonblocking(true); 然后调用recv_i， 无论收到多少字节，都会立即返回， 但未避免数据完整，你需要自己组装完整的应用层协议包， 具体逻辑可参见bool xxtcp_client::do_read(xxp2p_io_ctx\* ctx) 这个函数
2.一旦close socket, 阻塞接收会立即结束，并且返回值<=0

**Comment by xschool2010** [comment]
好的 谢谢 我试试
