### ISSUE TITLE
是否有考虑做下cocos2d-x的lua支持？

### ISSUE THREAD

**Issue by puckery** [simdsoft/yasio#8]
如题

**Comment by halx99** [comment]
我们游戏是用lua, 在用这个，lua支持很简单的，如果用async_tcp_client 则只需要导出收发接口即可

**Comment by halx99** [comment]
以后会做到更方便集成

**Comment by puckery** [comment]
看了下asio现在有独立出来的版本，集成方便了很多，可以考虑用独立版本的asio封装一套接口，简洁一些。

**Comment by halx99** [comment]
嗯，是的，曾经用过asio, 其实找一个好一点的导出方案就行

**Comment by halx99** [comment]
use sol2

**Comment by halx99** [comment]
最新版本已支持Lua
