### ISSUE TITLE
Does the project contain source codes with tools/pcode_autog.exe ?

### ISSUE THREAD

**Issue by EricDDK** [simdsoft/yasio#99]

**Comment by halx99** [comment]
Yes, but it is not update more than 3 years.

**Comment by EricDDK** [comment]
> Yes, but it is not update more than 3 years.

Okay thank you.

**Comment by halx99** [comment]
@EricDDK Hi, I make a update for pcode_autog.exe and sync latest source code to github: https://github.com/halx99/pcode_autog
